// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uxurwxyehuwriauslrcc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV4dXJ3eHllaHV3cmlhdXNscmNjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE4MDI0MTIsImV4cCI6MjA1NzM3ODQxMn0.5Km6XYO9HyqT86bEjGVkGbM_kpe3rRJ5OMoGy3B9QOg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);